import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

export type GeneratedByInkDAgent = {
  _id: string;
  name: string;
} | null;

export function CampaignBlogInkDAgentAttribution({
  agent,
  className,
}: {
  agent?: GeneratedByInkDAgent;
  className?: string;
}) {
  const agentName = String(agent?.name ?? "").trim();

  if (!agentName) return null;

  return (
    <div
      className={cn(
        "inline-flex items-center gap-2 rounded-full border border-[#DCE8F5] bg-[#F4F8FD] px-3 py-1.5 text-[11px] font-medium text-[#35516B]",
        className,
      )}
    >
      <Sparkles className="h-3.5 w-3.5 text-[#5B4DF7]" />
      <span>
        Generated by InkD agent{" "}
        <span className="font-semibold text-[#132238]">{agentName}</span>
      </span>
    </div>
  );
}
