import {
  GIF_OPTIMIZATION_COMMANDS,
  GIF_OPTIMIZATION_LARGE_FILE_COMMANDS,
  GIF_OPTIMIZATION_LARGE_FILE_THRESHOLD_BYTES,
  GIF_OPTIMIZATION_TARGET_MAX_BYTES,
  GIF_OPTIMIZATION_TARGET_MIN_BYTES,
} from "./asset-optimization.constants";

export const GIF_MIN_TARGET_BYTES = GIF_OPTIMIZATION_TARGET_MIN_BYTES;
export const GIF_MAX_UPLOAD_BYTES = GIF_OPTIMIZATION_TARGET_MAX_BYTES;
export const GIF_WORKER_INPUT_NAME = "input.gif";
export const GIF_STAGE_TIMEOUT_MS = 9_000;
export const GIF_TOTAL_TIMEOUT_MS = 24_000;
export const GIF_LARGE_FILE_THRESHOLD_BYTES =
  GIF_OPTIMIZATION_LARGE_FILE_THRESHOLD_BYTES;

export const GIF_COMPRESSION_COMMANDS = GIF_OPTIMIZATION_COMMANDS;

export const GIF_LARGE_FILE_COMPRESSION_COMMANDS =
  GIF_OPTIMIZATION_LARGE_FILE_COMMANDS;
