import {
  IMAGE_OPTIMIZATION_INITIAL_QUALITY,
  IMAGE_OPTIMIZATION_MAX_LONG_EDGE_PX,
  IMAGE_OPTIMIZATION_OUTPUT_MIME_TYPE,
  IMAGE_OPTIMIZATION_TARGET_MAX_SIZE_MB,
} from "./asset-optimization.constants";

export const IMAGE_UPLOAD_COMPRESSION_MAX_LONG_EDGE_PX =
  IMAGE_OPTIMIZATION_MAX_LONG_EDGE_PX;
export const IMAGE_UPLOAD_COMPRESSION_TARGET_MAX_SIZE_MB =
  IMAGE_OPTIMIZATION_TARGET_MAX_SIZE_MB;
export const IMAGE_UPLOAD_COMPRESSION_OUTPUT_MIME_TYPE =
  IMAGE_OPTIMIZATION_OUTPUT_MIME_TYPE;
export const IMAGE_UPLOAD_COMPRESSION_INITIAL_QUALITY =
  IMAGE_OPTIMIZATION_INITIAL_QUALITY;
