import { Rocket } from "lucide-react";

import { CampaignSocialPublishRateLimitTooltip } from "@/components/campaign/social/campaign-social-publish-rate-limit-tooltip";
import { Button } from "@/components/ui/button";
import { getCampaignSocialPublishRateLimitDisabledReason } from "@/lib/campaign/social";
import type {
  CampaignInkDAutoSocialPublishConfig,
  CampaignSocialPublishRateLimits,
} from "@/types/campaigns";

export function InkDAutoSocialPublishCard(props: {
  config: CampaignInkDAutoSocialPublishConfig | null | undefined;
  disabledReason: string | null;
  publishRateLimits: CampaignSocialPublishRateLimits | null;
  onOpenModal: () => void;
}) {
  const enabled = !!props.config?.enabled;
  const statusLabel = enabled ? "Enabled" : "Disabled";
  const imageLabel = props.config?.imageUrl
    ? "Custom image selected"
    : "Default fallback image";
  const rateLimitDisabledReason = getCampaignSocialPublishRateLimitDisabledReason(
    {
      resetAt: props.publishRateLimits?.resetAt ?? null,
      user: props.publishRateLimits?.user ?? null,
      campaign: props.publishRateLimits?.campaign ?? null,
      blog: null,
    },
  );

  return (
    <section className="rounded-[28px] border border-[#D9E4EC] bg-white p-5 shadow-sm">
      <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
        <div className="min-w-0">
          <div className="flex items-center gap-3">
            <div className="rounded-2xl bg-[#EEF9FB] p-3 text-[#0EA5A5]">
              <Rocket className="h-5 w-5" />
            </div>
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#0EA5A5]">
                Campaign automation
              </p>
              <h2 className="mt-1.5 text-xl font-medium text-[#132238]">
                Automatic social publishing
              </h2>
            </div>
          </div>

          <p className="mt-4 max-w-3xl text-sm leading-6 text-[#64748B]">
            When enabled, xPoll will automatically publish campaign blogs
            generated by connected InkD agents for this campaign to all social
            accounts that are connected and enabled at execution time.
          </p>

          <div className="mt-4 flex flex-wrap gap-2">
            <span
              className={
                enabled
                  ? "rounded-full bg-[#E8FBFB] px-3 py-1 text-xs font-medium text-[#0B7272]"
                  : "rounded-full bg-[#F4F4F5] px-3 py-1 text-xs font-medium text-[#52525B]"
              }
            >
              {statusLabel}
            </span>
            <span className="rounded-full bg-[#F1F5F9] px-3 py-1 text-xs font-medium text-[#516274]">
              {imageLabel}
            </span>
            <CampaignSocialPublishRateLimitTooltip
              user={props.publishRateLimits?.user ?? null}
              campaign={props.publishRateLimits?.campaign ?? null}
              blogRule={props.publishRateLimits?.blogRule ?? null}
              resetAt={props.publishRateLimits?.resetAt ?? null}
              triggerClassName="bg-[#F8FBFD]"
            />
          </div>

          {props.disabledReason ? (
            <p className="mt-3 text-sm text-[#B45309]">
              {props.disabledReason}
            </p>
          ) : null}
          {!props.disabledReason && rateLimitDisabledReason ? (
            <p className="mt-3 text-sm text-[#7C3AED]">
              Automatic social publishing will be skipped until the current rate
              limit resets.
            </p>
          ) : null}
        </div>

        <div className="shrink-0">
          <Button
            type="button"
            variant="outline"
            className="rounded-full border-[#D9E4EC] px-5 text-sm font-medium text-[#132238]"
            onClick={props.onOpenModal}
            disabled={!!props.disabledReason}
          >
            {enabled ? "Manage consent" : "Set up auto publish"}
          </Button>
        </div>
      </div>
    </section>
  );
}
